version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mini_task_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: minitaskdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mini_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db          # ชี้ไปที่ชื่อ service ของ MySQL ใน compose (คือ "db")
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8081:80"           # เปิดใช้ผ่าน http://localhost:8081

volumes:
  dbdata:
